# Generated by Django 3.2.14 on 2022-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('picture', models.ImageField(upload_to='pics/')),
            ],
        ),
    ]
