# Generated by Django 3.2.14 on 2022-08-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_remove_operator_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='phoneNo',
        ),
    ]
