# Generated by Django 3.2.14 on 2022-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20220825_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='name',
        ),
        migrations.AddField(
            model_name='operator',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
    ]
