# Generated by Django 3.2.14 on 2022-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20220825_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='picture',
            field=models.ImageField(default='img/default-avatar.png', upload_to='pics/'),
        ),
    ]
